services:
  openzoe:
    image: SEU_USUARIO/openzoe:latest
    container_name: openzoe_app
    ports:
      - "8550:8550"
      - "4242:4242"
    volumes:
      - ./openzoe/data:/app/data
    restart: unless-stopped
